var questions = [
  {
    "question": "Name A Country Where You Think The United States Has Spies",
    "answer1": "Russia",
    "answer2": "Iraq",
    "answer3": "Afghanistan",
    "answer4": "China",
    "answer5": "Japan",
    "answer6": "Iran",
    "answer7": "Germany",
    "answer1point": 37,
    "answer2point": 17,
    "answer3point": 11,
    "answer4point": 7,
    "answer5point": 7,
    "answer6point": 5,
    "answer7point": 4,
    "questionsLength": 7
  },
  {
    "question": "Name Something Specific That People Climb",
    "answer1": "Mountains",
    "answer2": "Trees",
    "answer3": "Stairs",
    "answer4": "Ladder",
    "answer5": "Rocks",
    "answer1point": 54,
    "answer2point": 28,
    "answer3point": 7,
    "answer4point": 6,
    "answer5point": 3,
    "questionsLength": 5

  },
  {
    "question": "Name A Sport That Does Not Contain The Word 'ball'",
    "answer1": "Hockey",
    "answer2": "Soccer",
    "answer3": "Golf",
    "answer4": "Tennis",
    "answer5": "Swimming",
    "answer1point": 32,
    "answer2point": 27,
    "answer3point": 13,
    "answer4point": 11,
    "answer5point": 5,
    "questionsLength": 5,
    "alternateanswers5": "Swim"

  },
  {
    "question": "Name An Important City In The Art World",
    "answer1": "Paris",
    "answer2": "New York",
    "answer3": "Rome",
    "answer4": "Philadelphia",
    "answer5": "Venice",
    "answer1point": 44,
    "answer2point": 28,
    "answer3point": 13,
    "answer4point": 11,
    "answer5point": 6,
    "questionsLength": 5
  },
  {
    "question": "Name Something Twins Might Share While Growing Up",
    "answer1": "Clothes",
    "answer2": "Bedroom",
    "answer3": "Friends",
    "answer4": "Toys",
    "answer1point": 54,
    "answer2point": 30,
    "answer3point": 4,
    "answer4point": 3,
    "questionsLength": 4,
    "alternateanswers2": "Room"

  },
  {
    "question": "Name An Occupation In Which Scandals Are Always Happening",
    "answer1": "Politician",
    "answer2": "Actor",
    "answer3": "Priest",
    "answer4": "Banker",
    "answer5": "Lawyer",
    "answer6": "Policeman",
    "answer1point": 47,
    "answer2point": 24,
    "answer3point": 4,
    "answer4point": 4,
    "answer5point": 4,
    "answer6point": 3,
    "questionsLength": 6,
    "alternateanswers6": "Police"

  },
  {
    "question": "Name Something That Gets Very Fragile When Old",
    "answer1": "People",
    "answer2": "Paper",
    "answer3": "Books",
    "answer4": "Pictures",
    "answer5": "Eggs",
    "answer6": "Flowers",
    "answer1point": 52,
    "answer2point": 25,
    "answer3point": 5,
    "answer4point": 4,
    "answer5point": 2,
    "answer6point": 2,
    "questionsLength": 6,
    "alternateanswers2": "Plants"

  },
  {
    "question": "Name Someplace You Go Where People Often Seem To Be In A Hurry",
    "answer1": "Airport",
    "answer2": "Bank",
    "answer3": "Grocery Store",
    "answer4": "Work",
    "answer5": "DownTown",
    "answer1point": 26,
    "answer2point": 12,
    "answer3point": 11,
    "answer4point": 9,
    "answer5point": 9,
    "questionsLength": 5,
    "alternateanswers3": "Store"

  },
  {
    "question": "Name Something That Could Spring A Leak",
    "answer1": "Faucet",
    "answer2": "Pipes",
    "answer3": "Hose",
    "answer4": "Waterbed",
    "answer5": "Boat",
    "answer1point": 35,
    "answer2point": 27,
    "answer3point": 11,
    "answer4point": 9,
    "answer5point": 4,
    "questionsLength": 5
  },
  {
    "question": "Name Something Of Yours That's Falling Apart",
    "answer1": "Body",
    "answer2": "Life",
    "answer3": "Car",
    "answer4": "House",
    "answer5": "Furniture",
    "answer1point": 27,
    "answer2point": 24,
    "answer3point": 16,
    "answer4point": 13,
    "answer5point": 8,
    "questionsLength": 5

  },
  {
    "question": "Name A Precious Stone Or Gem",
    "answer1": "Diamond",
    "answer2": "Ruby",
    "answer3": "Emerald",
    "answer4": "Opal",
    "answer5": "Pearl",
    "answer1point": 75,
    "answer2point": 15,
    "answer3point": 5,
    "answer4point": 2,
    "answer5point": 2,
    "questionsLength": 5
  },
  {
    "question": "Name Something People Take With Them To The Basement When A Tornado Is Coming",
    "answer1": "Food",
    "answer2": "Water",
    "answer3": "Flashlight",
    "answer4": "Phone",
    "answer5": "Children",
    "answer1point": 33,
    "answer2point": 22,
    "answer3point": 21,
    "answer4point": 7,
    "answer5point": 7,
    "questionsLength": 5,
    "alternateanswers3": "Light", 
    "alternateanswers4": "Cellphone",
    "alternateanswers5": "Kids"
  },
  {
    "question": "Name An Animal That People Ride",
    "answer1": "Horse",
    "answer2": "Camel",
    "answer3": "Donkey",
    "answer1point": 88,
    "answer2point": 4,
    "answer3point": 3,
    "questionsLength": 3
  },
  {
    "question": "We Asked 100 Women... Which Occupation Has The Best Dressed Men",
    "answer1": "Lawyer",
    "answer2": "Athlete",
    "answer3": "Model",
    "answer4": "Military",
    "answer5": "Doctor",
    "answer6": "Police",
    "answer1point": 30,
    "answer2point": 24,
    "answer3point": 15,
    "answer4point": 10,
    "answer5point": 4,
    "answer6point": 3,
    "questionsLength": 6,
    "alternateanswers6": "Policeman"

  },
  {
    "question": "Tell Me One Word You'd Really Hope People Would Use In Describing The Kind Of Person You Are",
    "answer1": "Kind",
    "answer2": "Honest",
    "answer3": "Caring",
    "answer4": "Funny",
    "answer5": "Nice",
    "answer6": "Friendly",
    "answer1point": 24,
    "answer2point": 10,
    "answer3point": 7,
    "answer4point": 6,
    "answer5point": 6,
    "answer6point": 4,
    "questionsLength": 6
  },
  {
    "question": "Name A U.S. State That You'd Consider Moving To When You Retire",
    "answer1": "Florida",
    "answer2": "California",
    "answer3": "Arizona",
    "answer4": "Hawaii",
    "answer5": "Texas",
    "answer6": "Georgia",
    "answer7": "North Carolina",
    "answer1point": 33,
    "answer2point": 19,
    "answer3point": 8,
    "answer4point": 7,
    "answer5point": 7,
    "answer6point": 4,
    "answer7point": 4,
    "questionsLength": 7
  },
  {
    "question": "Name An Article Of Clothing That Hardly Ever Changes Style",
    "answer1": "Underwear",
    "answer2": "Pants",
    "answer3": "Socks",
    "answer4": "Sweaters",
    "answer5": "Suits",
    "answer1point": 33,
    "answer2point": 24,
    "answer3point": 20,
    "answer4point": 4,
    "answer5point": 3,
    "questionsLength": 5,
    "alternateanswers2": "Jeans"
  },
  {
    "question": "Name A Topic Of Conversation At Men's Poker Games",
    "answer1": "Women",
    "answer2": "Sports",
    "answer3": "Job",
    "answer4": "Money",
    "answer5": "Car",
    "answer1point": 74,
    "answer2point": 16,
    "answer3point": 3,
    "answer4point": 3,
    "answer5point": 2,
    "questionsLength": 5,
    "alternateanswers3": "Work",

  }

]